<!DOCTYPE html>
<html lang="en"><head>
<script src="Group3_Final_Presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="Group3_Final_Presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="Group3_Final_Presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="Group3_Final_Presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="Group3_Final_Presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Group3_Final_Presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="Group3_Final_Presentation_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Yushan Huang">
  <meta name="author" content="Sora Hosoda">
  <meta name="author" content="Grace Sen">
  <meta name="author" content="Sandy Zhu">
  <meta name="author" content="Jungmin Woo">
  <meta name="dcterms.date" content="2026-08-12">
  <title>Digital Marketing Campaign Analytics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="Group3_Final_Presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="Group3_Final_Presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="Group3_Final_Presentation_files/libs/revealjs/dist/theme/quarto-0fde88a82f0356838740f155f1088782.css">
  <link href="Group3_Final_Presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="Group3_Final_Presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="Group3_Final_Presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="Group3_Final_Presentation_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="Group3_Final_Presentation_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="Group3_Final_Presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Digital Marketing Campaign Analytics</h1>
  <p class="subtitle">Group Project Final Report Presentation</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Yushan Huang 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Sora Hosoda 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Grace Sen 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Sandy Zhu 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Jungmin Woo 
</div>
</div>
</div>

  <p class="date">2026-08-12</p>
</section>
<section id="table-of-contents" class="slide level2 scrollable">
<h2>Table of Contents</h2>
<ol type="1">
<li class="fragment">Introduction</li>
<li class="fragment">Population / Sample &amp; Sample Characteristics</li>
<li class="fragment">Analytics Objective 1 — <em>Yushan Huang</em> - Marketing Channels and Campaign Types</li>
<li class="fragment">Analytics Objective 2 — <em>Jungmin Woo</em> - Campaign Performance</li>
<li class="fragment">Analytics Objective 3 — <em>Grace Sen</em> - Customer Demographics and Conversion</li>
<li class="fragment">Analytics Objective 4 — <em>Sandy Zhu</em> - Customer Interaction and Purchase Behavior</li>
<li class="fragment">Analytics Objective 5 — <em>Sora Hosoda</em> - Predictive Analytics</li>
<li class="fragment">Conclusion</li>
<li class="fragment">Appendix</li>
</ol>
</section>
<section>
<section id="introduction" class="title-slide slide level1 center">
<h1>Introduction</h1>

</section>
<section id="problem-definition" class="slide level2">
<h2>Problem Definition</h2>
<p>Digital marketing teams use multiple campaign channels and campaign strategies to reach customers, but it is not always clear which approaches are most strongly associated with customer conversion. Without data-driven evidence, marketing resources may be allocated to channels or campaign types that do not meaningfully improve conversion outcomes.</p>
<ul>
<li><strong>Context:</strong> The dataset represents multi-channel digital marketing campaigns, including Social Media, Email, PPC, Referral, and SEO.</li>
<li><strong>Business gap:</strong> Marketers need clearer evidence about which campaign characteristics and customer behaviors are associated with successful conversion.</li>
<li><strong>Decision need:</strong> Identify actionable patterns that can support better campaign design, targeting, engagement, and resource allocation.</li>
</ul>
</section>
<section id="research-objectives" class="slide level2">
<h2>Research Objectives</h2>
<ul>
<li class="fragment"><strong>RO1:</strong> To analyze how different marketing channels and campaign types affect customer conversion. — linked to AO1</li>
<li class="fragment"><strong>RO2:</strong> Impact of Campaign Channel and Type on Customer Conversion</li>
<li class="fragment"><strong>RO3:</strong> To examine whether customer demographic characteristics influence the likelihood of digital marketing conversion.</li>
<li class="fragment"><strong>RO4:</strong> To evaluate how customer interaction and previous purchasing behavior relate to short-term marketing response and customer conversion, and to identify the most important behavioral drivers of conversion.</li>
<li class="fragment"><strong>RO5:</strong> To develop a predictive model that identifies the most useful factors for predicting customer conversion using customer demographics, campaign information, engagement variables, and purchase history.</li>
</ul>
</section>
<section id="importance-of-the-research" class="slide level2">
<h2>Importance of the Research</h2>
<ul>
<li><strong>Improve marketing effectiveness:</strong> Understanding the factors associated with conversion can help marketers make more informed decisions about campaign strategy and customer targeting.</li>
<li><strong>Support resource allocation:</strong> Comparing marketing channels and campaign types can reveal whether conversion outcomes differ meaningfully across marketing approaches.</li>
<li><strong>Generate customer insights:</strong> Examining engagement, purchasing behavior, and loyalty-related measures can help explain how customers respond throughout the digital marketing journey.</li>
<li><strong>Apply predictive analytics:</strong> Classification and ensemble methods provide a systematic way to evaluate conversion patterns and assess how useful marketing and behavioral variables are for prediction.</li>
<li><strong>Business stakeholders:</strong> The findings can support marketing managers, campaign planners, and customer analytics teams when designing and evaluating future campaigns.</li>
</ul>
</section></section>
<section>
<section id="population-sample" class="title-slide slide level1 center">
<h1>Population / Sample</h1>

</section>
<section id="population-sample-1" class="slide level2">
<h2>Population / Sample</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href=""></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb1-3"><a href=""></a><span class="fu">library</span>(vip)         <span class="co"># variable importance</span></span>
<span id="cb1-4"><a href=""></a><span class="fu">library</span>(DALEX)        <span class="co"># PDP / SHAP-style explanations</span></span>
<span id="cb1-5"><a href=""></a><span class="fu">library</span>(DALEXtra)</span>
<span id="cb1-6"><a href=""></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-7"><a href=""></a></span>
<span id="cb1-8"><a href=""></a><span class="fu">tidymodels_prefer</span>()</span>
<span id="cb1-9"><a href=""></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>))</span>
<span id="cb1-10"><a href=""></a></span>
<span id="cb1-11"><a href=""></a>raw_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"digital_marketing_campaign_dataset.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-12"><a href=""></a></span>
<span id="cb1-13"><a href=""></a><span class="fu">glimpse</span>(raw_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 8,000
Columns: 20
$ CustomerID          &lt;dbl&gt; 8000, 8001, 8002, 8003, 8004, 8005, 8006, 8007, 80…
$ Age                 &lt;dbl&gt; 56, 69, 46, 32, 60, 25, 38, 56, 36, 40, 28, 28, 41…
$ Gender              &lt;chr&gt; "Female", "Male", "Female", "Female", "Female", "F…
$ Income              &lt;dbl&gt; 136912, 41760, 88456, 44085, 83964, 42925, 25615, …
$ CampaignChannel     &lt;chr&gt; "Social Media", "Email", "PPC", "PPC", "PPC", "Soc…
$ CampaignType        &lt;chr&gt; "Awareness", "Retention", "Awareness", "Conversion…
$ AdSpend             &lt;dbl&gt; 6497.8701, 3898.6686, 1546.4296, 539.5259, 1678.04…
$ ClickThroughRate    &lt;dbl&gt; 0.04391851, 0.15572507, 0.27749037, 0.13761125, 0.…
$ ConversionRate      &lt;dbl&gt; 0.08803141, 0.18272468, 0.07642272, 0.08800419, 0.…
$ WebsiteVisits       &lt;dbl&gt; 0, 42, 2, 47, 0, 6, 42, 48, 13, 22, 47, 16, 13, 8,…
$ PagesPerVisit       &lt;dbl&gt; 2.399017, 2.917138, 8.223619, 4.540939, 2.046847, …
$ TimeOnSite          &lt;dbl&gt; 7.396803, 5.352549, 13.794901, 14.688363, 13.99337…
$ SocialShares        &lt;dbl&gt; 19, 5, 0, 89, 6, 95, 54, 96, 73, 14, 94, 23, 28, 8…
$ EmailOpens          &lt;dbl&gt; 6, 2, 11, 2, 6, 5, 14, 9, 4, 8, 16, 18, 16, 8, 16,…
$ EmailClicks         &lt;dbl&gt; 9, 7, 2, 2, 6, 8, 3, 3, 8, 4, 5, 6, 5, 1, 8, 1, 8,…
$ PreviousPurchases   &lt;dbl&gt; 4, 2, 8, 0, 8, 0, 6, 0, 5, 8, 6, 5, 4, 2, 1, 1, 8,…
$ LoyaltyPoints       &lt;dbl&gt; 688, 3459, 2337, 2463, 4345, 3316, 930, 2983, 460,…
$ AdvertisingPlatform &lt;chr&gt; "IsConfid", "IsConfid", "IsConfid", "IsConfid", "I…
$ AdvertisingTool     &lt;chr&gt; "ToolConfid", "ToolConfid", "ToolConfid", "ToolCon…
$ Conversion          &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,…</code></pre>
</div>
</div>
<ul>
<li><strong>Population:</strong> Customers exposed to the company’s digital marketing campaigns</li>
<li><strong>Sample:</strong> 8,000 customers, 20 variables</li>
<li><strong>Sampling frame / period:</strong> The dataset does not provide a specific campaign period or geographic region.</li>
</ul>
</section>
<section id="data-cleaning" class="slide level2">
<h2>Data Cleaning</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">campaign_data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">8000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gender</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Fem: 4839, Mal: 3161</td>
</tr>
<tr class="even">
<td style="text-align: left;">CampaignChannel</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Ref: 1719, PPC: 1655, Ema: 1557, SEO: 1550</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CampaignType</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Con: 2077, Awa: 1988, Con: 1988, Ret: 1947</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conversion</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Yes: 7012, No: 988</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">43.63</td>
<td style="text-align: right;">14.90</td>
<td style="text-align: right;">18.00</td>
<td style="text-align: right;">31.00</td>
<td style="text-align: right;">43.00</td>
<td style="text-align: right;">56.00</td>
<td style="text-align: right;">69.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">Income</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">84664.20</td>
<td style="text-align: right;">37580.39</td>
<td style="text-align: right;">20014.00</td>
<td style="text-align: right;">51744.50</td>
<td style="text-align: right;">84926.50</td>
<td style="text-align: right;">116815.75</td>
<td style="text-align: right;">149986.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AdSpend</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5000.94</td>
<td style="text-align: right;">2838.04</td>
<td style="text-align: right;">100.05</td>
<td style="text-align: right;">2523.22</td>
<td style="text-align: right;">5013.44</td>
<td style="text-align: right;">7407.99</td>
<td style="text-align: right;">9997.91</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">ClickThroughRate</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ConversionRate</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">WebsiteVisits</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">24.75</td>
<td style="text-align: right;">14.31</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">13.00</td>
<td style="text-align: right;">25.00</td>
<td style="text-align: right;">37.00</td>
<td style="text-align: right;">49.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PagesPerVisit</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.55</td>
<td style="text-align: right;">2.61</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3.30</td>
<td style="text-align: right;">5.53</td>
<td style="text-align: right;">7.84</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">TimeOnSite</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.73</td>
<td style="text-align: right;">4.23</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">7.68</td>
<td style="text-align: right;">11.48</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SocialShares</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">49.80</td>
<td style="text-align: right;">28.90</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">25.00</td>
<td style="text-align: right;">50.00</td>
<td style="text-align: right;">75.00</td>
<td style="text-align: right;">99.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">EmailOpens</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.48</td>
<td style="text-align: right;">5.71</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">14.00</td>
<td style="text-align: right;">19.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EmailClicks</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.47</td>
<td style="text-align: right;">2.86</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">PreviousPurchases</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.49</td>
<td style="text-align: right;">2.89</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LoyaltyPoints</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2490.27</td>
<td style="text-align: right;">1429.53</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1254.75</td>
<td style="text-align: right;">2497.00</td>
<td style="text-align: right;">3702.25</td>
<td style="text-align: right;">4999.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="sample-characteristics" class="slide level2">
<h2>Sample Characteristics</h2>

<img data-src="Group3_Final_Presentation_files/figure-revealjs/sample-char-1-1.png" width="864" class="r-stretch"></section>
<section id="sample-characteristics-cont." class="slide level2">
<h2>Sample Characteristics (cont.)</h2>

<img data-src="Group3_Final_Presentation_files/figure-revealjs/sample-char-2-1.png" width="864" class="r-stretch"><ul>
<li>Overall conversion rate: 88% (class-imbalanced — relevant for classification AOs)</li>
<li>The sample includes customers across a wide range of ages and income levels.</li>
<li>Customers were exposed to five digital marketing channels: Social Media, Email, PPC, Referral, and SEO.</li>
<li>The overall conversion rate is approximately <strong>87.7%</strong>, indicating a strong class imbalance that should be considered when evaluating classification models.</li>
</ul>
<!-- =================================================================== -->
<!-- AO1 — left blank for Member 1 to fill in                            -->
<!-- =================================================================== -->
</section></section>
<section>
<section id="analytics-objective-1-yushan-huang" class="title-slide slide level1 center">
<h1>Analytics Objective 1 — <em>Yushan Huang</em></h1>

</section>
<section id="ao1-marketing-channels-and-campaign-types" class="slide level2">
<h2>AO1: Marketing Channels and Campaign Types</h2>
<blockquote>
<p><strong>RO1:</strong> To analyze how different marketing channels and campaign types affect customer conversion.</p>
</blockquote>
<ul>
<li><strong>Target variable:</strong> <code>Conversion</code> (No / Yes)</li>
<li><strong>Independent variables:</strong> <code>CampaignChannel</code>, <code>CampaignType</code></li>
<li><strong>Problem type:</strong> Binary classification</li>
<li><strong>Business question:</strong> Which marketing channels and campaign types are associated with higher customer conversion?</li>
<li><strong>Analytical focus:</strong> Compare group-level conversion patterns and test whether channel/type alone can predict individual conversion.</li>
</ul>
</section>
<section id="ao1-machine-learning-methods-to-be-used" class="slide level2">
<h2>AO1: Machine Learning Methods to be Used</h2>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Regression-Focused Methods</a></li><li><a href="#tabset-1-2">Classification-Focused Methods</a></li><li><a href="#tabset-1-3">Ensembles</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<ul>
<li>Not used because <code>Conversion</code> is a binary outcome.</li>
<li>Logistic regression is used as a <strong>classification</strong> model and provides interpretable odds ratios.</li>
</ul>
</div>
<div id="tabset-1-2">
<ul>
<li>Logistic Regression — interpretable baseline for estimating the direction and magnitude of associations</li>
<li>Decision Tree — captures possible non-linear splits and interactions</li>
</ul>
</div>
<div id="tabset-1-3">
<ul>
<li>Random Forest — compares an ensemble classifier with simpler models and provides variable importance</li>
</ul>
</div>
</div>
</div>
</section>
<section id="ao1-data-wrangling-visualization" class="slide level2">
<h2>AO1: Data Wrangling &amp; Visualization</h2>

<img data-src="Group3_Final_Presentation_files/figure-revealjs/ao1-wrangle-1.png" width="960" class="r-stretch"><ul>
<li>Overall conversion rate: <strong>87.6%</strong></li>
<li>Channel conversion rates are tightly clustered (about <strong>86.8%–88.3%</strong>), suggesting only small raw differences across channels.</li>
<li><code>Conversion</code> campaigns have the highest conversion rate (<strong>93.4%</strong>), compared with roughly <strong>85.6%–85.8%</strong> for the other campaign types.</li>
</ul>
</section>
<section id="ao1-channel-campaign-type-pattern" class="slide level2">
<h2>AO1: Channel × Campaign Type Pattern</h2>

<img data-src="Group3_Final_Presentation_files/figure-revealjs/ao1-heatmap-1.png" width="864" class="r-stretch"><ul>
<li>The strongest combinations are <strong>SEO + Conversion (94.0%)</strong> and <strong>PPC + Conversion (94.0%)</strong>.</li>
<li>The <code>Conversion</code> campaign type is consistently the highest-performing type across all five channels.</li>
<li>This pattern suggests that <strong>campaign purpose/type is more strongly associated with conversion than channel choice</strong> in this sample.</li>
</ul>
</section>
<section id="ao1-model-fitting" class="slide level2">
<h2>AO1: Model Fitting</h2>
<ul>
<li><strong>Split:</strong> 80% training / 20% testing, stratified by <code>Conversion</code></li>
<li><strong>Recipe:</strong> dummy encoding + zero-variance removal</li>
<li><strong>Models:</strong> Logistic Regression, Decision Tree, Random Forest</li>
<li><strong>Primary metric:</strong> ROC AUC, because the outcome is imbalanced (about 88% conversions)</li>
</ul>
</section>
<section id="ao1-prediction-model-evaluation" class="slide level2">
<h2>AO1: Prediction &amp; Model Evaluation</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  model               Accuracy ROC_AUC Sensitivity Specificity
  &lt;chr&gt;                  &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
1 Decision Tree          0.876   0.5             1           0
2 Logistic Regression    0.876   0.554           1           0
3 Random Forest          0.876   0.535           1           0</code></pre>
</div>

</div>
<img data-src="Group3_Final_Presentation_files/figure-revealjs/ao1-eval-1.png" width="768" class="r-stretch"><ul>
<li>A naive model that predicts <strong>“Yes” for everyone</strong> already achieves about <strong>87.7% accuracy</strong>, so accuracy alone is misleading.</li>
<li>The more informative comparison is <strong>ROC AUC</strong>, which tests whether the models can distinguish converters from non-converters across thresholds.</li>
<li>If ROC AUC remains close to 0.50–0.60, <code>CampaignChannel</code> and <code>CampaignType</code> alone have <strong>limited individual-level predictive power</strong>, even though campaign type shows a clear group-level pattern.</li>
</ul>
</section>
<section id="ao1-interpretation" class="slide level2">
<h2>AO1: Interpretation</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 7
  term                  estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 CampaignType_Convers…    2.49      0.125    7.28   3.31e-13    1.95       3.19
2 CampaignChannel_PPC      1.09      0.122    0.710  4.78e- 1    0.859      1.38
3 CampaignChannel_Refe…    1.05      0.120    0.410  6.82e- 1    0.830      1.33
4 CampaignChannel_Soci…    1.02      0.122    0.147  8.83e- 1    0.801      1.29
5 CampaignChannel_SEO      0.997     0.122   -0.0215 9.83e- 1    0.786      1.27
6 CampaignType_Retenti…    0.972     0.102   -0.276  7.83e- 1    0.797      1.19
7 CampaignType_Conside…    0.958     0.101   -0.426  6.70e- 1    0.786      1.17</code></pre>
</div>

</div>
<img data-src="Group3_Final_Presentation_files/figure-revealjs/ao1-interpret-1.png" width="864" class="r-stretch"><ul>
<li>Logistic-regression odds ratios show the direction and relative size of differences after accounting for the other predictor.</li>
<li>The largest practical contrast is expected for <strong><code>CampaignType = Conversion</code></strong>, consistent with its 93.4% raw conversion rate.</li>
<li>Random Forest importance can show whether campaign type or channel contributes more to prediction, but importance should be interpreted cautiously if ROC AUC is weak.</li>
</ul>
</section>
<section id="ao1-summary-findings" class="slide level2">
<h2>AO1: Summary Findings</h2>
<ul>
<li class="fragment"><strong>Campaign type matters more than marketing channel:</strong> conversion rates across channels are very similar (<strong>86.8%–88.3%</strong>), while campaign types show a wider difference.</li>
<li class="fragment"><strong>Conversion-focused campaigns perform best:</strong> their conversion rate is approximately <strong>93.4%</strong>, versus about <strong>85.6%–85.8%</strong> for Awareness, Consideration, and Retention campaigns.</li>
<li class="fragment">The pattern is consistent across channels: every channel performs best when the campaign type is <code>Conversion</code>; <strong>SEO + Conversion (94.0%)</strong> and <strong>PPC + Conversion (94.0%)</strong> are the strongest observed combinations.</li>
<li class="fragment"><strong>Predictive caution:</strong> because the overall conversion rate is already <strong>87.7%</strong>, high accuracy can be achieved by predicting the majority class. ROC AUC is therefore more useful for judging true discrimination.</li>
<li class="fragment"><strong>Business implication:</strong> prioritize the design and targeting of conversion-focused campaigns rather than reallocating budget solely on the basis of channel. Channel decisions should also consider cost, reach, and audience fit.</li>
</ul>
<!-- =================================================================== -->
<!-- AO2 — left blank for Member 2 to fill in                            -->
<!-- =================================================================== -->
</section></section>
<section>
<section id="analytics-objective-2-jungmin-woo" class="title-slide slide level1 center">
<h1>Analytics Objective 2 — <em>Jungmin Woo</em></h1>

</section>
<section id="ao2-campaign-performance" class="slide level2 smaller">
<h2>AO2: Campaign Performance</h2>
<blockquote>
<p>RO2: Analyze the impact of marketing channels and campaign types on customer conversion.</p>
</blockquote>
<ul>
<li><strong>IV (predictors):</strong> <code>CampaignChannel</code>, <code>CampaignType</code> (both categorical)</li>
<li><strong>DV (target):</strong> <code>Conversion</code> (binary — Yes / No)</li>
<li><strong>Problem type:</strong> Classification</li>
<li>Only these two categorical variables are used as predictors, so this AO isolates the effect of <em>channel</em> and <em>campaign type</em> on conversion, independent of demographic or on-site behavior variables</li>
</ul>
</section>
<section id="ao2-machine-learning-methods-to-be-used" class="slide level2">
<h2>AO2: Machine Learning Methods to be Used</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Regression-Focused Methods</a></li><li><a href="#tabset-2-2">Classification-Focused Methods</a></li><li><a href="#tabset-2-3">Ensembles</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<ul>
<li>Not applicable (outcome is categorical)</li>
</ul>
</div>
<div id="tabset-2-2">
<ul>
<li>Logistic Regression</li>
<li>Decision Tree (classification)</li>
</ul>
</div>
<div id="tabset-2-3">
<ul>
<li>Random Forest (classification)</li>
</ul>
</div>
</div>
</div>
</section>
<section id="ao2-data-wrangling-visualization" class="slide level2">
<h2>AO2: Data Wrangling &amp; Visualization</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  CampaignChannel CampaignType Conversion
            &lt;int&gt;        &lt;int&gt;      &lt;int&gt;
1               0            0          0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 4
   CampaignChannel CampaignType  ConversionRate     N
   &lt;fct&gt;           &lt;fct&gt;                  &lt;dbl&gt; &lt;int&gt;
 1 SEO             Conversion             0.940   402
 2 PPC             Conversion             0.940   447
 3 Email           Conversion             0.933   416
 4 Referral        Conversion             0.930   445
 5 Social Media    Conversion             0.924   367
 6 Referral        Awareness              0.884   431
 7 PPC             Consideration          0.869   404
 8 SEO             Retention              0.866   389
 9 Social Media    Retention              0.862   370
10 Referral        Retention              0.860   436
11 PPC             Awareness              0.859   412
12 PPC             Retention              0.857   392
13 Email           Consideration          0.856   403
14 Referral        Consideration          0.855   407
15 Social Media    Consideration          0.849   405
16 SEO             Awareness              0.849   390
17 SEO             Consideration          0.848   369
18 Email           Retention              0.844   360
19 Email           Awareness              0.841   378
20 Social Media    Awareness              0.841   377</code></pre>
</div>
</div>

<img data-src="Group3_Final_Presentation_files/figure-revealjs/ao2-viz-1.png" width="864" class="r-stretch"><ul>
<li>No missing values in <code>CampaignChannel</code>, <code>CampaignType</code>, or <code>Conversion</code></li>
<li>The bar chart shows very little spread <strong>across channels</strong> within each campaign type (bars of the same color are roughly the same height), but a clear gap <strong>across campaign types</strong>: <code>CampaignType == "Conversion"</code> sits noticeably higher (~92–94%) than <code>Awareness</code>, <code>Consideration</code>, or <code>Retention</code> (~84–88%) in every channel</li>
<li>This suggests campaign <em>type</em> may matter more than campaign <em>channel</em> for conversion — tested formally below</li>
</ul>
</section>
<section id="ao2-model-fitting" class="slide level2">
<h2>AO2: Model Fitting</h2>
</section>
<section id="ao2-prediction-model-evaluation" class="slide level2">
<h2>AO2: Prediction &amp; Model Evaluation</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 4
  model               .metric  .estimator .estimate
  &lt;chr&gt;               &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 Decision Tree       accuracy binary         0.876
2 Logistic Regression accuracy binary         0.876
3 Random Forest       accuracy binary         0.876
4 Decision Tree       f_meas   binary         0.934
5 Logistic Regression f_meas   binary         0.934
6 Random Forest       f_meas   binary         0.934
7 Decision Tree       roc_auc  binary         0.5  
8 Logistic Regression roc_auc  binary         0.554
9 Random Forest       roc_auc  binary         0.546</code></pre>
</div>
</div>
<ul>
<li>All three models land at essentially the same accuracy (~87.6%), which matches the overall base rate of <code>Conversion == "Yes"</code> in the data — the models are not beating a “always predict Yes” baseline on accuracy alone</li>
<li>ROC AUC is low (~0.53–0.54, just above the 0.50 random-guess line), meaning <code>CampaignChannel</code> and <code>CampaignType</code> alone have only weak discriminative power for <em>individual-level</em> conversion, even though the group-level rates in the bar chart differ by type</li>
<li>This is a common pattern: a variable can show a real, statistically significant <em>group-level</em> effect while still being a weak <em>individual-level</em> predictor, because most of the variation in who converts is driven by other factors (behavioral, demographic) not included in this AO by design</li>
</ul>
</section>
<section id="ao2-interpretation" class="slide level2">
<h2>AO2: Interpretation</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(campaign_data$CampaignChannel, campaign_data$Conversion)
X-squared = 2.7849, df = 4, p-value = 0.5944</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(campaign_data$CampaignType, campaign_data$Conversion)
X-squared = 84.454, df = 3, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  term                         estimate std.error statistic  p.value
  &lt;chr&gt;                           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                   1.77        0.106   16.7    6.21e-63
2 CampaignType_Conversion       0.911       0.125    7.28   3.31e-13
3 CampaignChannel_PPC           0.0864      0.122    0.710  4.78e- 1
4 CampaignType_Consideration   -0.0429      0.101   -0.426  6.70e- 1
5 CampaignChannel_Referral      0.0492      0.120    0.410  6.82e- 1
6 CampaignType_Retention       -0.0280      0.102   -0.276  7.83e- 1
7 CampaignChannel_Social.Media  0.0179      0.122    0.147  8.83e- 1
8 CampaignChannel_SEO          -0.00262     0.122   -0.0215 9.83e- 1</code></pre>
</div>

</div>
<img data-src="Group3_Final_Presentation_files/figure-revealjs/ao2-interpret-1.png" width="768" class="r-stretch"><ul>
<li>The chi-square test for <code>CampaignChannel</code> is <strong>not significant</strong> (χ² ≈ 2.78, p ≈ 0.59) — channel choice alone shows no reliable association with conversion</li>
<li>The chi-square test for <code>CampaignType</code> <strong>is significant</strong> (χ² ≈ 84.5, p &lt; 0.001) — campaign type is meaningfully associated with conversion, driven mainly by the <code>"Conversion"</code> type having a substantially higher rate (~93%) than <code>Awareness</code>/<code>Consideration</code>/<code>Retention</code> (~84–88%)</li>
<li>Random Forest variable importance should echo this: dummy variables for <code>CampaignType</code> should rank above <code>CampaignChannel</code> dummies</li>
</ul>
</section>
<section id="ao2-summary-findings" class="slide level2">
<h2>AO2: Summary Findings</h2>
<ul>
<li class="fragment"><strong>Campaign type</strong> has a statistically significant relationship with conversion; <strong>campaign channel</strong> does not, at least on its own</li>
<li class="fragment">The higher conversion rate for <code>CampaignType == "Conversion"</code> campaigns is expected by design (these campaigns are explicitly built to drive conversion) but confirms the labeling is consistent with actual outcomes</li>
<li class="fragment">Despite the significant group-level association, channel + type alone give weak individual-level predictive power (ROC AUC ≈ 0.53) — they are not sufficient by themselves to identify which specific customers will convert</li>
<li class="fragment"><strong>Business implication:</strong> channel selection appears interchangeable for conversion purposes in this data, so budget allocation decisions should weigh cost-per-channel and other KPIs rather than assuming any one channel converts better; campaign <em>type</em> mix (more bottom-funnel “Conversion”-type campaigns) is the lever more strongly tied to conversion outcomes</li>
</ul>
<!-- =================================================================== -->
<!-- AO3 — Customer Demographics and Conversion                            -->
<!-- =================================================================== -->
</section></section>
<section>
<section id="analytics-objective-3-grace-sen" class="title-slide slide level1 center">
<h1>Analytics Objective 3 — <em>Grace Sen</em></h1>

</section>
<section id="do-demographics-help-identify-customers-who-convert" class="slide level2" data-background-color="#1E4D2B">
<h2>Do demographics help identify customers who convert?</h2>
<h3 id="analytics-objective-3">Analytics Objective 3</h3>
<p>Examine whether <strong>age, gender, and income</strong> are associated with—and useful for predicting—customer conversion.</p>
<div class="objective-line">
<p><strong>Predictors:</strong> Age · Gender · Income<br>
<strong>Outcome:</strong> Conversion (binary classification)</p>
</div>
<aside class="notes">
<p>My analytics objective asks whether customer demographics help explain and predict conversion. I use age, gender, and income as predictors and conversion as the binary outcome. The analysis compares an interpretable logistic regression with a nonlinear ensemble model.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao3-data-wrangling-visualization-sample-and-outcome" class="slide level2">
<h2>AO3: Data Wrangling &amp; Visualization — Sample and Outcome</h2>
<div class="columns">
<div class="column" style="width:48%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-1-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:48%;">
<ul>
<li><strong>8000 customers</strong></li>
<li><strong>0 missing values</strong> in AO3 variables</li>
<li>Conversion rate: 87.6%</li>
</ul>
<div class="key-message">
<p>Accuracy alone is misleading: predicting “Converted” for everyone already produces high accuracy.</p>
</div>
<p><strong>Primary metrics:</strong> ROC AUC, PR AUC, balanced accuracy, sensitivity, and specificity.</p>
</div></div>
<aside class="notes">
<p>The dataset contains 8,000 customers and no missing values in the four variables used here. Conversion is highly imbalanced. Because almost nine out of ten customers converted, accuracy can look strong even when a model does not separate the two classes. I therefore emphasize discrimination and class-balanced metrics.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao3-data-wrangling-visualization-income-and-gender" class="slide level2">
<h2>AO3: Data Wrangling &amp; Visualization — Income and Gender</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-2-1.png" width="652"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-3-1.png" width="652"></p>
</figure>
</div>
</div>
</div>
</div></div>
<div class="takeaway">
<p>Neither income nor gender appears to distinguish converters from non-converters on its own.</p>
</div>
<aside class="notes">
<p>The descriptive patterns already suggest weak demographic effects. Income medians and distributions substantially overlap across outcomes, while conversion rates are nearly equal across gender groups. These plots are descriptive, so the models next test whether the variables work better jointly.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao3-data-wrangling-visualization-age" class="slide level2">
<h2>AO3: Data Wrangling &amp; Visualization — Age</h2>

<img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-4-1.png" width="1008" class="r-stretch"><div class="takeaway">
<p>Age provides little visible univariate discrimination across nearly the entire range.</p>
</div>
<aside class="notes">
<p>The age density curves overlap across almost the full distribution. Taken together, the exploratory results provide little evidence that any single demographic variable strongly separates the outcome classes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao3-machine-learning-methods-model-fitting" class="slide level2 smaller scrollable">
<h2>AO3: Machine Learning Methods &amp; Model Fitting</h2>
<div class="columns">
<div class="column" style="width:46%;">
<h3 id="logistic-regression">Logistic regression</h3>
<ul>
<li>Interpretable adjusted associations</li>
<li>Standardized age and income</li>
<li>Odds ratios with 95% confidence intervals</li>
</ul>
<h3 id="random-forest">Random forest</h3>
<ul>
<li>Captures nonlinearities and interactions</li>
<li>500 trees</li>
<li>Five-fold stratified cross-validation</li>
<li>Tuned <code>mtry</code> and minimum node size</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="leakage-safe-evaluation">Leakage-safe evaluation</h3>
<ol type="1">
<li>Stratified <strong>75/25 train–test split</strong></li>
<li>Training-only preprocessing recipe</li>
<li>Dummy-code gender; normalize numeric predictors</li>
<li>Tune the forest within training folds</li>
<li>Evaluate once on the untouched test set</li>
</ol>
<div class="key-message">
<p>The majority-class prediction serves as the benchmark.</p>
</div>
</div></div>
<aside class="notes">
<p>Logistic regression provides interpretable adjusted effects. Random forest tests whether nonlinear patterns or interactions add predictive value. The split is stratified, all preprocessing is learned on the training data only, and the test data remains untouched until final evaluation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao3-prediction-model-evaluation" class="slide level2">
<h2>AO3: Prediction &amp; Model Evaluation</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-5-1.png" width="768"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:36%;">
<h3 id="held-out-conclusion">Held-out conclusion</h3>
<p>Better-performing model: <strong>Random forest</strong></p>
<p>ROC AUC: 0.539</p>
<p>Balanced accuracy: 0.501</p>
<div class="key-message">
<p>Scores near 0.50 indicate little ability to rank converters above non-converters.</p>
</div>
</div></div>
<aside class="notes">
<p>On the held-out test set, the best demographic model has an ROC AUC and balanced accuracy near 0.50. That is approximately chance-level performance. High raw accuracy would not change this conclusion because the converted class dominates the sample.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao3-interpretation-logistic-regression" class="slide level2">
<h2>AO3: Interpretation — Logistic Regression</h2>
<div class="columns">
<div class="column" style="width:62%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-6-1.png" width="768"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:34%;">
<ul>
<li>Odds ratios near <strong>1.00</strong> indicate weak adjusted associations.</li>
<li>Intervals crossing <strong>1.00</strong> indicate limited evidence after controlling for the other demographics.</li>
<li>Association does not imply causation.</li>
</ul>
</div></div>
<aside class="notes">
<p>The logistic regression provides adjusted effects. Age and income are standardized, so each odds ratio represents a one-standard-deviation increase. Effects close to one, particularly with confidence intervals crossing one, support the same substantive conclusion as the held-out model evaluation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao3-interpretation-random-forest" class="slide level2">
<h2>AO3: Interpretation — Random Forest</h2>
<div class="columns">
<div class="column" style="width:62%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-7-1.png" width="768"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:34%;">
<p>Permutation importance ranks predictors <strong>within the fitted forest</strong>.</p>
<div class="key-message">
<p>A weak model can still rank weak predictors. Importance is relative and does not establish a business driver or causal effect.</p>
</div>
</div></div>
<aside class="notes">
<p>The random forest still produces a ranking because permutation importance is relative. We should not describe the top-ranked demographic as a strong driver when the entire model performs near chance. Variable importance also does not establish causality.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao3-summary-findings" class="slide level2">
<h2>AO3: Summary Findings</h2>
<div class="columns">
<div class="column" style="width:48%;">
<h3 id="what-ao3-found">What AO3 found</h3>
<ul>
<li>Demographic distributions overlap substantially.</li>
<li>Both models showed weak test-set discrimination.</li>
<li>Demographics alone are insufficient for targeting.</li>
</ul>
</div><div class="column" style="width:48%;">
<h3 id="business-implication">Business implication</h3>
<ul>
<li>Prioritize behavioral and engagement signals.</li>
<li>Use demographics for segmentation and fairness checks.</li>
<li>Validate the final model on external data.</li>
</ul>
</div></div>
<p><strong>Takeaway:</strong> Customer behavior is more promising than demographics for predicting conversion.</p>
<aside class="notes">
<p>The overall conclusion is that demographics alone do not meaningfully distinguish converters from non-converters. The business should prioritize engagement variables such as website visits, time on site, email activity, prior purchases, and campaign interactions. Demographics may remain useful for segmentation and fairness monitoring, but not as the primary targeting inputs.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- =================================================================== -->
<!-- AO4 —  Customer Interaction, Purchase Behavior, and Conversion                           -->
<!-- =================================================================== -->
</section></section>
<section>
<section id="analytics-objective-4-sandy-zhu" class="title-slide slide level1 center">
<h1>Analytics Objective 4 — <em>Sandy Zhu</em></h1>

</section>
<section id="ao4-customer-interaction-purchase-behavior-and-conversion" class="slide level2">
<h2>AO4: Customer Interaction, Purchase Behavior, and Conversion</h2>
<p>RO4: How do email engagement (EmailOpens and EmailClicks) and previous purchases affect customer conversion, and which factor is the most important for predicting conversion?</p>
<ul>
<li><strong>Target variables:</strong> <code>ConversionRate</code>, <code>Conversion</code> (No / Yes)</li>
<li><strong>Independent variables:</strong> <code>EmailOpens</code>, <code>EmailClicks</code>, <code>PreviousPurchases</code></li>
<li><strong>Problem type:</strong> Regression and binary classification</li>
</ul>
</section>
<section class="slide level2">

<ul>
<li><strong>Business question:</strong> How do email engagement and previous purchases relate to customer conversion?</li>
<li><strong>Analytical focus:</strong> Compare models and identify which customer behavior is most important for predicting conversion.</li>
</ul>
</section>
<section id="ao4-machine-learning-methods-to-be-used" class="slide level2">
<h2>AO4: Machine Learning Methods to be Used</h2>
<h3 id="regression-focused-method">Regression-Focused Method</h3>
<ul>
<li><strong>Linear Regression</strong> — predicts <code>ConversionRate</code> as a continuous marketing outcome.</li>
</ul>
<h3 id="classification-focused-method">Classification-Focused Method</h3>
<ul>
<li><strong>Logistic Regression</strong> — predicts whether a customer converts (<code>Yes</code> / <code>No</code>).</li>
</ul>
</section>
<section class="slide level2">

<h3 id="ensemble-method">Ensemble Method</h3>
<ul>
<li><strong>Random Forest</strong> — captures nonlinear patterns and identifies important behavioral predictors.</li>
</ul>
</section>
<section id="ao4-data-wrangling-visualization" class="slide level2">
<h2>AO4: Data Wrangling &amp; Visualization</h2>

<img data-src="Group3_Final_Presentation_files/figure-revealjs/ao4-wrangle-1.png" width="960" class="r-stretch"><ul>
<li>The dataset contains <strong>8,000 customers</strong>, with no missing values in the variables used for RO4.</li>
<li>Approximately <strong>87.7%</strong> of customers converted, indicating substantial class imbalance in the binary outcome.</li>
<li>Customers who converted generally show higher <code>EmailOpens</code>, <code>EmailClicks</code>, and <code>PreviousPurchases</code> than non-converters.</li>
<li>These descriptive patterns suggest that customer interaction and prior purchasing behavior may contain useful information for predicting conversion.</li>
</ul>
</section>
<section id="ao4-customer-behavior-conversion-pattern" class="slide level2">
<h2>AO4: Customer Behavior × Conversion Pattern</h2>

<img data-src="Group3_Final_Presentation_files/figure-revealjs/ao4-behavior-pattern-1.png" width="960" class="r-stretch"><ul>
<li>Converted customers show <strong>higher email engagement</strong> (median opens: <strong>10 vs.&nbsp;6</strong>; clicks: <strong>5 vs.&nbsp;3</strong>).</li>
<li>They also have <strong>more previous purchases</strong>, suggesting stronger engagement is associated with conversion.</li>
</ul>
</section>
<section id="ao4-model-fitting" class="slide level2">
<h2>AO4: Model Fitting</h2>
<ul>
<li><strong>Split:</strong> 80% training / 20% testing, stratified by <code>Conversion</code></li>
<li><strong>Regression model:</strong> Linear Regression predicts <code>ConversionRate</code></li>
<li><strong>Classification models:</strong> Logistic Regression, Decision Tree, and Random Forest predict <code>Conversion</code></li>
<li><strong>Purpose:</strong> compare interpretable linear/classification methods with tree-based and ensemble approaches.</li>
</ul>
</section>
<section id="ao4-prediction-model-evaluation" class="slide level2">
<h2>AO4: Prediction &amp; Model Evaluation</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard    0.0559  
2 rsq     standard    0.000587
3 mae     standard    0.0490  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  model               Accuracy ROC_AUC Sensitivity Specificity
  &lt;chr&gt;                  &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
1 Decision Tree          0.876   0.5         1          0     
2 Logistic Regression    0.876   0.656       1          0     
3 Random Forest          0.868   0.637       0.977      0.0960</code></pre>
</div>

</div>
<img data-src="Group3_Final_Presentation_files/figure-revealjs/ao4-eval-1.png" width="768" class="r-stretch"><ul>
<li><strong>Regression:</strong> Linear Regression is evaluated using RMSE, MAE, and R² to determine how well customer behavior predicts <code>ConversionRate</code>.</li>
</ul>
</section>
<section class="slide level2">

<ul>
<li><strong>Classification:</strong> Logistic Regression, Decision Tree, and Random Forest are compared using the same held-out test set.</li>
<li>Because approximately <strong>87.7% of customers converted</strong>, accuracy alone may overstate model performance.</li>
<li><strong>ROC AUC is the primary classification metric</strong>, because it measures how well each model distinguishes converters from non-converters across probability thresholds.</li>
</ul>
</section>
<section id="ao4-interpretation" class="slide level2">
<h2>AO4: Interpretation</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term              estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 EmailClicks           1.52    0.0406     10.3  5.87e-25     1.40      1.65
2 EmailOpens            1.52    0.0405     10.3  5.80e-25     1.40      1.64
3 PreviousPurchases     1.47    0.0401      9.57 1.10e-21     1.36      1.59</code></pre>
</div>

</div>
<img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-8-1.png" width="960" class="r-stretch"><ul>
<li><strong>PreviousPurchases</strong> is the strongest predictor, followed by <strong>EmailOpens</strong> and <strong>EmailClicks</strong>.</li>
<li>Purchase history appears to be more useful for predicting conversion than email engagement alone.</li>
<li>The model has <strong>moderate predictive power (ROC AUC = 0.656)</strong>, so the results should be interpreted with caution.</li>
</ul>
</section>
<section id="ao4-summary-findings" class="slide level2 incremental">
<h2>AO4: Summary Findings</h2>
<ul>
<li><p>Higher <strong>EmailOpens, EmailClicks, and PreviousPurchases</strong> are associated with higher conversion.</p></li>
<li><p><strong>PreviousPurchases</strong> is the strongest predictor, followed by <strong>EmailOpens</strong> and <strong>EmailClicks</strong>.</p></li>
<li><p>Model performance is <strong>moderate (ROC AUC = 0.656)</strong>; the <strong>87.6% conversion rate</strong> also means accuracy alone can be misleading.</p></li>
<li><p><strong>Business implication:</strong> use both <strong>purchase history and email engagement</strong> to identify customers with higher conversion potential.</p></li>
</ul>
</section>
<!-- =================================================================== -->
<!-- AO5 — Impact of Campaign Channel and Type on Customer Conversion    -->
<!-- =================================================================== --></section>
<section>
<section id="analytics-objective-5-sora-hosoda" class="title-slide slide level1 center">
<h1>Analytics Objective 5 — <em>Sora Hosoda</em></h1>

</section>
<section id="ao5-predictive-analytics" class="slide level2">
<h2>AO5: Predictive Analytics</h2>
<blockquote>
<p><strong>Research Objective:</strong> To develop a predictive model that identifies the most useful factors for predicting customer conversion using customer demographics, campaign information, engagement variables, and purchase history.</p>
</blockquote>
<ul>
<li><strong>Outcome:</strong> <code>Conversion</code> (Yes / No)</li>
<li><strong>Predictors:</strong> 15 customer and marketing variables</li>
<li><strong>Problem type:</strong> Binary classification</li>
<li><strong>Analytical focus:</strong> Compare multiple classification models and identify the strongest predictors of conversion.</li>
</ul>
<div class="key-message">
<p>Which factors are most useful for predicting customer conversion when all major predictor groups are considered together?</p>
</div>
<aside class="notes">
<p>This objective combines customer demographics, campaign information, engagement variables, and purchase history in one overall predictive analysis.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao5-machine-learning-methods-to-be-used" class="slide level2">
<h2>AO5: Machine Learning Methods to be Used</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Regression-Focused Methods</a></li><li><a href="#tabset-3-2">Classification-Focused Methods</a></li><li><a href="#tabset-3-3">Ensembles</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<ul>
<li>Not used because <code>Conversion</code> is a binary outcome.</li>
<li>The analysis focuses on classification models.</li>
</ul>
</div>
<div id="tabset-3-2">
<ul>
<li><strong>Logistic Regression</strong> — interpretable baseline classification model</li>
<li><strong>Decision Tree</strong> — captures nonlinear decision rules and interactions</li>
</ul>
</div>
<div id="tabset-3-3">
<ul>
<li><strong>Random Forest</strong> — combines many decision trees</li>
<li><strong>XGBoost</strong> — sequentially builds trees to improve prediction</li>
</ul>
</div>
</div>
</div>
<div class="takeaway">
<p>Four models were compared to determine whether ensemble methods improve prediction over simpler classification models.</p>
</div>
</section>
<section id="ao5-data-wrangling-visualization" class="slide level2">
<h2>AO5: Data Wrangling &amp; Visualization</h2>
<div class="columns">
<div class="column" style="width:56%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 17%">
<col style="width: 82%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor Group</th>
<th style="text-align: left;">Variables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Customer Profile</td>
<td style="text-align: left;">Age, Gender, Income</td>
</tr>
<tr class="even">
<td style="text-align: left;">Campaign</td>
<td style="text-align: left;">Channel, Type, Ad Spend</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Engagement</td>
<td style="text-align: left;">CTR, Website Visits, Pages per Visit, Time on Site, Email Activity, Social Shares</td>
</tr>
<tr class="even">
<td style="text-align: left;">History</td>
<td style="text-align: left;">Previous Purchases, Loyalty Points</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Conversion</th>
<th style="text-align: left;">Customers</th>
<th style="text-align: left;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">7,012</td>
<td style="text-align: left;">87.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">No</td>
<td style="text-align: left;">988</td>
<td style="text-align: left;">12.4%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Class imbalance:</strong> About 88% of customers converted.</p>
</div></div>
<div class="takeaway">
<p>Because the outcome is highly imbalanced, ROC AUC was prioritized over accuracy when comparing models.</p>
</div>
<aside class="notes">
<p>The analysis uses 15 predictors from four broad categories. Conversion is highly imbalanced, so accuracy alone can be misleading.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao5-model-fitting" class="slide level2 scrollable">
<h2>AO5: Model Fitting</h2>
<div class="columns">
<div class="column" style="width:48%;">
<h3 id="data-splitting">Data Splitting</h3>
<ul>
<li><strong>80% training / 20% testing</strong></li>
<li>Stratified by <code>Conversion</code></li>
<li>Test data held out for final evaluation</li>
</ul>
<h3 id="recipe-creation">Recipe Creation</h3>
<ul>
<li>Median imputation</li>
<li>Novel and unknown factor handling</li>
<li>Dummy encoding</li>
<li>Zero-variance removal</li>
</ul>
</div><div class="column" style="width:48%;">
<h3 id="model-specification">Model Specification</h3>
<ol type="1">
<li>Logistic Regression</li>
<li>Decision Tree</li>
<li>Random Forest</li>
<li>XGBoost</li>
</ol>
<h3 id="model-selection">Model Selection</h3>
<ul>
<li><strong>10-fold stratified cross-validation</strong></li>
<li>Hyperparameter tuning for ensemble models</li>
<li>Primary metric: <strong>ROC AUC</strong></li>
</ul>
</div></div>
<div class="key-message">
<p>The same training data and cross-validation framework were used to compare model performance.</p>
</div>
<aside class="notes">
<p>The data was split before model development. Cross-validation was conducted within the training data, while the test set remained untouched until final evaluation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao5-prediction-model-evaluation" class="slide level2">
<h2>AO5: Prediction &amp; Model Evaluation</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-11-1.png" width="720"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:36%;">
<h3 id="best-model-xgboost">Best Model: XGBoost</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Test Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ROC AUC</td>
<td style="text-align: right;"><strong>0.844</strong></td>
</tr>
<tr class="even">
<td>Accuracy</td>
<td style="text-align: right;"><strong>91.8%</strong></td>
</tr>
<tr class="odd">
<td>Sensitivity</td>
<td style="text-align: right;"><strong>99.5%</strong></td>
</tr>
<tr class="even">
<td>Specificity</td>
<td style="text-align: right;"><strong>37.4%</strong></td>
</tr>
</tbody>
</table>
<p><strong>Confusion Matrix</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Actual Yes</th>
<th style="text-align: right;">Actual No</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Predicted Yes</td>
<td style="text-align: right;"><strong>1,396</strong></td>
<td style="text-align: right;">124</td>
</tr>
<tr class="even">
<td>Predicted No</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;"><strong>74</strong></td>
</tr>
</tbody>
</table>
</div></div>
<div class="takeaway">
<p>XGBoost achieved the highest cross-validation ROC AUC and the strongest overall test performance.</p>
</div>
<aside class="notes">
<p>XGBoost had the highest cross-validation ROC AUC at 0.818. On the test set, ROC AUC increased to 0.844. Sensitivity was very high, although non-converters remained more difficult to identify.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao5-interpretation-variable-importance-shap" class="slide level2">
<h2>AO5: Interpretation — Variable Importance &amp; SHAP</h2>
<div class="columns">
<div class="column" style="width:48%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-12-1.png" width="633"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:48%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-13-1.png" width="633"></p>
</figure>
</div>
</div>
</div>
</div></div>
<div class="takeaway">
<p>SHAP identified <code>CampaignType_Conversion</code>, EmailClicks, PreviousPurchases, ClickThroughRate, LoyaltyPoints, and PagesPerVisit as leading contributors to prediction.</p>
</div>
<aside class="notes">
<p>Variable importance and SHAP provide complementary views of the fitted XGBoost model. The interpretation indicates that campaign, engagement, and customer-history information contributed strongly to prediction.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao5-interpretation-partial-dependence-plot" class="slide level2">
<h2>AO5: Interpretation — Partial Dependence Plot</h2>

<img data-src="Group3_Final_Presentation_files/figure-revealjs/unnamed-chunk-14-1.png" width="864" class="r-stretch"><div class="takeaway">
<p>Predicted conversion remained fairly stable at lower spending levels, increased around <strong>Ad Spend ≈ 5,000</strong>, and then remained relatively high.</p>
</div>
<aside class="notes">
<p>The PDP describes the relationship learned by the model. It should not be interpreted as evidence that increasing ad spend directly causes conversion.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ao5-summary-findings" class="slide level2">
<h2>AO5: Summary Findings</h2>
<div class="columns">
<div class="column" style="width:48%;">
<h3 id="model-findings">Model Findings</h3>
<ul>
<li><strong>XGBoost</strong> was the strongest model.</li>
<li>CV ROC AUC = <strong>0.818</strong></li>
<li>Test ROC AUC = <strong>0.844</strong></li>
<li>Very high sensitivity = <strong>99.5%</strong></li>
<li>Non-converters remained harder to identify.</li>
</ul>
</div><div class="column" style="width:48%;">
<h3 id="interpretation">Interpretation</h3>
<ul>
<li>Campaign type contributed strongly.</li>
<li>Email engagement was important.</li>
<li>Previous purchases and loyalty contributed.</li>
<li>Website engagement also mattered.</li>
<li>Demographics contributed less.</li>
</ul>
</div></div>
<div class="key-message">
<p><strong>Customer actions, campaign context, and purchase history were more useful for predicting conversion than demographic characteristics alone.</strong></p>
</div>
<aside class="notes">
<p>Overall, XGBoost provided the strongest predictive performance. The interpretation results indicate that campaign context, engagement, and previous customer behavior were more useful than demographics for predicting conversion.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="conclusion" class="title-slide slide level1 center">
<h1>Conclusion</h1>

</section>
<section id="key-findings" class="slide level2">
<h2>Key Findings</h2>
<ul>
<li><strong>Campaign type mattered more than channel:</strong> Conversion-focused campaigns had the highest conversion rates.</li>
<li><strong>Customer behavior was useful for prediction:</strong> Engagement, previous purchases, loyalty, and website activity contributed to conversion prediction.</li>
<li><strong>Demographics had limited predictive value:</strong> Age, gender, and income were weaker predictors.</li>
<li><strong>XGBoost performed best:</strong> CV ROC AUC = <strong>0.818</strong> and test ROC AUC = <strong>0.844</strong>.</li>
<li><strong>Class imbalance mattered:</strong> About <strong>88%</strong> of customers converted, so accuracy alone was not sufficient.</li>
</ul>
</section>
<section id="recommendations-for-businesses" class="slide level2">
<h2>Recommendations for Businesses</h2>
<ul>
<li><strong>Focus on customer behavior:</strong> Use engagement and purchase history to support customer targeting.</li>
<li><strong>Consider campaign type:</strong> Conversion-focused campaigns showed stronger conversion results.</li>
<li><strong>Do not rely on channel alone:</strong> Also consider cost, reach, and audience fit.</li>
<li><strong>Use predictive models for targeting:</strong> XGBoost can combine multiple customer and campaign factors.</li>
<li><strong>Evaluate models beyond accuracy:</strong> Consider ROC AUC, sensitivity, and specificity.</li>
</ul>
</section>
<section id="limitations-and-directions-for-future-research" class="slide level2">
<h2>Limitations and Directions for Future Research</h2>
<ul>
<li><strong><code>Conversion</code> is not clearly defined:</strong> The dataset does not specify what customer action counts as a conversion.</li>
<li><strong>The outcome is imbalanced:</strong> Non-converters were more difficult to identify.</li>
<li><strong>Time and location are not provided:</strong> The dataset does not specify a campaign period or geographic region.</li>
<li><strong>The results are not causal:</strong> The analysis identifies associations and predictive patterns.</li>
<li><strong>The findings come from one dataset:</strong> Future research should test other datasets and customer populations.</li>
<li><strong>Future research should clearly define conversion</strong> and explore ways to improve prediction of non-converters.</li>
</ul>
</section>
<section id="appendix" class="slide level2">
<h2>Appendix</h2>
<ul>
<li><strong>GitHub Repo:</strong> <a href="https://github.com/gracesen/IBM6540-Group3" class="uri">https://github.com/gracesen/IBM6540-Group3</a></li>
<li><strong>GitHub Pages:</strong> <a href="https://gracesen.github.io/IBM6540-Group3/" class="uri">https://gracesen.github.io/IBM6540-Group3/</a></li>
<li><strong>Presentation Slides:</strong> <a href="https://gracesen.github.io/IBM6540-Group3/final_report_presentation_2.html" class="uri">https://gracesen.github.io/IBM6540-Group3/final_report_presentation_2.html</a></li>
</ul>
</section>
<section id="thank-you-qa" class="slide level2">
<h2>Thank You / Q&amp;A</h2>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="Group3_Final_Presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="Group3_Final_Presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="Group3_Final_Presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="Group3_Final_Presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="Group3_Final_Presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="Group3_Final_Presentation_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="Group3_Final_Presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="Group3_Final_Presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="Group3_Final_Presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="Group3_Final_Presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="Group3_Final_Presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 6.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>